#!/usr/bin/env bash

export BASEROW_AMOUNT_OF_WORKERS=${BASEROW_AMOUNT_OF_WORKERS:-1}
export BASEROW_AMOUNT_OF_GUNICORN_WORKERS=${BASEROW_AMOUNT_OF_GUNICORN_WORKERS:-3}

export DATABASE_PASSWORD=$CLOUDRON_POSTGRESQL_PASSWORD
export DATABASE_NAME=$CLOUDRON_POSTGRESQL_DATABASE
export DATABASE_HOST=$CLOUDRON_POSTGRESQL_HOST
export DATABASE_USER=$CLOUDRON_POSTGRESQL_USER
export DATABASE_PORT=$CLOUDRON_POSTGRESQL_PORT
export DOMAIN="https://$CLOUDRON_APP_DOMAIN"
export CADDY_LISTEN_PORT=":80"

export TMPDIR=/run/temp
export DJANGO_SETTINGS_MODULE='baserow.config.settings.cloudron'
