# Generated by Django 3.2.6 on 2022-02-08 20:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_alter_application_name_squashed_0014_alter_group_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("database", "0060_set_ordering_on_tablewebhook_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="AirtableImportJob",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("airtable_share_id", models.CharField(max_length=18)),
                ("progress_percentage", models.IntegerField(default=0)),
                ("state", models.CharField(max_length=128)),
                ("error", models.TextField(blank=True, default="")),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.group"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
