# Generated by Django 3.2.13 on 2022-05-30 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_settings_allow_reset_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="storage_usage",
            field=models.IntegerField(null=True),
        ),
    ]
